# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0006_auto_20160316_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggerindex',
            name='num_processes',
            field=models.IntegerField(default=1),
        ),
    ]
